default_platform(:mac)

platform :mac do
  before_all do
    APP_PROJECT = "EssentialFeed.xcodeproj"
    APP_WORKSPACE = "EssentialFeed.xcworkspace"
    TEST_DEVICES = [ "My Mac" ]
    SCHEME = "CI"
  end

  desc "Run Mac OS unit tests"
  lane :unit_tests do
    run_tests(
        workspace: APP_WORKSPACE,
        scheme: SCHEME,
        code_coverage: true,
        build_for_testing: true,
        open_report: true
    )
  end

  desc "Generate code coverage"
  lane :code_coverage do
    xcov(
      workspace: APP_WORKSPACE,
      scheme: SCHEME,
      only_project_targets: true,
      output_directory: "xcov_output",
      minimum_coverage_percentage: 29.0,
      json_report: true,
      html_report: true
    )
  end
end
